#include <inttypes.h>
#include "ops.h"

uint32_t default_program[] = {
    OP_SUB, 1, OP_PUSH, 16777215, OP_PUSH, 0, OP_PUSH, 0, OP_PUSH, 2, OP_URGENCY,
    OP_PUSH, 75, OP_BRIGHTNESS, OP_SUB, 2, OP_RAND, OP_PUSH, 12632256, OP_OR,
    OP_PUSH, 0, OP_WRITE, OP_WIDTH, OP_PUSH, 2, OP_WRITE, OP_SUB, 4, OP_PUSH, 0,
    OP_FOREGROUND, OP_FILL, OP_PUSH, 0, OP_READ, OP_FOREGROUND, OP_PUSH, 2,
    OP_READ, OP_PUSH, 5, OP_SET_CURSOR, OP_PUSH, 83, OP_PUTCHAR, OP_PUSH, 116,
    OP_PUTCHAR, OP_PUSH, 101, OP_PUTCHAR, OP_PUSH, 114, OP_PUTCHAR, OP_PUSH, 108,
    OP_PUTCHAR, OP_PUSH, 105, OP_PUTCHAR, OP_PUSH, 110, OP_PUTCHAR, OP_PUSH, 103,
    OP_PUTCHAR, OP_PUSH, 2, OP_READ, OP_PUSH, 1, OP_MIN, OP_PUSH, 2, OP_WRITE,
    OP_TICK, OP_PUSH, REG_CURSOR_X, OP_GET, OP_PUSH, 2147483648, OP_GT, OP_NOT,
    OP_PUSH, 6, OP_CMP, OP_PUSH, 5, OP_GOTO, OP_SUB, 6, OP_PUSH, 4, OP_GOTO,
    OP_SUB, 5, OP_TICK, OP_TICK, OP_PUSH, 13434777, OP_PUSH, 0, OP_WRITE,
    OP_WIDTH, OP_PUSH, 2, OP_WRITE, OP_SUB, 7, OP_PUSH, 0, OP_FOREGROUND, OP_FILL,
    OP_PUSH, 0, OP_READ, OP_FOREGROUND, OP_PUSH, 2, OP_READ, OP_PUSH, 5,
    OP_SET_CURSOR, OP_PUSH, 90, OP_PUTCHAR, OP_PUSH, 105, OP_PUTCHAR, OP_PUSH,
    112, OP_PUTCHAR, OP_PUSH, 82, OP_PUTCHAR, OP_PUSH, 101, OP_PUTCHAR, OP_PUSH,
    99, OP_PUTCHAR, OP_PUSH, 114, OP_PUTCHAR, OP_PUSH, 117, OP_PUTCHAR, OP_PUSH,
    105, OP_PUTCHAR, OP_PUSH, 116, OP_PUTCHAR, OP_PUSH, 101, OP_PUTCHAR, OP_PUSH,
    114, OP_PUTCHAR, OP_PUSH, 2, OP_READ, OP_PUSH, 1, OP_MIN, OP_PUSH, 2,
    OP_WRITE, OP_TICK, OP_PUSH, REG_CURSOR_X, OP_GET, OP_PUSH, 2147483648, OP_GT,
    OP_NOT, OP_PUSH, 9, OP_CMP, OP_PUSH, 8, OP_GOTO, OP_SUB, 9, OP_PUSH, 7,
    OP_GOTO, OP_SUB, 8, OP_TICK, OP_TICK, OP_PUSH, 2, OP_GOTO, OP_SUB, 3,
    OP_RETURN, OP_HALT, OP_HALT
};
