// AUTOGENERATED FILE!!! DO NOT EDIT!!! See ops.p6

template <int W, int H, class P>
OpCodes<W,H,P>::OpCodes() {

    ops[OP_SUB]          = op_sub;
    ops[OP_RETURN]       = op_return;
    ops[OP_GOTO]         = op_goto;
    ops[OP_GOSUB]        = op_gosub;
    ops[OP_TICK]         = op_tick;
    ops[OP_TICK_MODE]    = op_tick_mode;
    ops[OP_NOOP]         = op_noop;
    ops[OP_CMP]          = op_cmp;
    ops[OP_CMPSUB]       = op_cmpsub;
    ops[OP_EQ]           = op_eq;
    ops[OP_LT]           = op_lt;
    ops[OP_LE]           = op_le;
    ops[OP_GT]           = op_gt;
    ops[OP_GE]           = op_ge;
    ops[OP_NE]           = op_ne;
    ops[OP_ADD]          = op_add;
    ops[OP_MIN]          = op_min;
    ops[OP_MUL]          = op_mul;
    ops[OP_DIV]          = op_div;
    ops[OP_MOD]          = op_mod;
    ops[OP_AND]          = op_and;
    ops[OP_OR]           = op_or;
    ops[OP_NOT]          = op_not;
    ops[OP_RAND]         = op_rand;
    ops[OP_WIDTH]        = op_width;
    ops[OP_HEIGHT]       = op_height;
    ops[OP_SET]          = op_set;
    ops[OP_GET]          = op_get;
    ops[OP_URGENCY]      = op_urgency;
    ops[OP_BRIGHTNESS]   = op_brightness;
    ops[OP_FOREGROUND]   = op_foreground;
    ops[OP_FILL]         = op_fill;
    ops[OP_PIXEL]        = op_pixel;
    ops[OP_PUSH]         = op_push;
    ops[OP_POP]          = op_pop;
    ops[OP_DUP]          = op_dup;
    ops[OP_SWAP]         = op_swap;
    ops[OP_MARK]         = op_mark;
    ops[OP_FILL_ROWS]    = op_fill_rows;
    ops[OP_MASK_ROWS]    = op_mask_rows;
    ops[OP_FILL_COLUMNS] = op_fill_columns;
    ops[OP_MASK_COLUMNS] = op_mask_columns;
    ops[OP_FILL_BITS]    = op_fill_bits;
    ops[OP_MASK_BITS]    = op_mask_bits;
    ops[OP_HALT]         = op_halt;
}

